name: mobile_m1
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

environment:
  sdk: '^3.8.0'